ALTER TABLE public.machines
  ADD COLUMN IF NOT EXISTS price_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS price_change_count integer NOT NULL DEFAULT 0;

UPDATE public.machines
SET price_updated_at = COALESCE(created_at, now())
WHERE price_updated_at IS NULL;

ALTER TABLE public.machines
  ALTER COLUMN price_updated_at SET DEFAULT now();

CREATE TABLE IF NOT EXISTS public.machine_price_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id text NOT NULL,
  product_name text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  old_prices jsonb NOT NULL,
  new_prices jsonb NOT NULL,
  changed_fields text[] NOT NULL DEFAULT ARRAY[]::text[],
  previous_values_known boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS machine_price_history_machine_date_idx
  ON public.machine_price_history (machine_id, changed_at DESC);

ALTER TABLE public.machine_price_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.machine_price_history FROM anon;
GRANT SELECT ON public.machine_price_history TO authenticated;

DROP POLICY IF EXISTS "Admins can read machine price history"
  ON public.machine_price_history;
CREATE POLICY "Admins can read machine price history"
  ON public.machine_price_history
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles AS profile
      WHERE profile.user_id = auth.uid()
        AND profile.is_admin IS TRUE
    )
  );

CREATE OR REPLACE FUNCTION public.record_machine_price_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  changed text[] := ARRAY[]::text[];
BEGIN
  IF OLD.mrp IS DISTINCT FROM NEW.mrp THEN
    changed := array_append(changed, 'mrp');
  END IF;
  IF OLD.sell_price IS DISTINCT FROM NEW.sell_price THEN
    changed := array_append(changed, 'sell_price');
  END IF;
  IF OLD.cost_price IS DISTINCT FROM NEW.cost_price THEN
    changed := array_append(changed, 'cost_price');
  END IF;

  IF cardinality(changed) > 0 THEN
    NEW.price_updated_at := now();
    NEW.price_change_count := COALESCE(OLD.price_change_count, 0) + 1;

    INSERT INTO public.machine_price_history (
      machine_id,
      product_name,
      changed_at,
      old_prices,
      new_prices,
      changed_fields,
      previous_values_known
    ) VALUES (
      NEW.id::text,
      NEW.name,
      NEW.price_updated_at,
      jsonb_build_object(
        'mrp', OLD.mrp,
        'sell_price', OLD.sell_price,
        'cost_price', OLD.cost_price
      ),
      jsonb_build_object(
        'mrp', NEW.mrp,
        'sell_price', NEW.sell_price,
        'cost_price', NEW.cost_price
      ),
      changed,
      true
    );
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.record_machine_price_change() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS machines_record_price_change
  ON public.machines;
CREATE TRIGGER machines_record_price_change
  BEFORE UPDATE OF mrp, sell_price, cost_price
  ON public.machines
  FOR EACH ROW
  EXECUTE FUNCTION public.record_machine_price_change();

-- The user confirmed the current Ultra Pro Max purchase cost was just updated.
-- Its prior value was not captured, so record the current value without inventing one.
WITH updated_machine AS (
  UPDATE public.machines
  SET price_updated_at = now(), price_change_count = 1
  WHERE name = 'N70 Ultra Pro Max'
    AND category = 'Rice mills and machines'
    AND COALESCE(price_change_count, 0) = 0
  RETURNING id::text AS machine_id, name, mrp, sell_price, cost_price, price_updated_at
)
INSERT INTO public.machine_price_history (
  machine_id,
  product_name,
  changed_at,
  old_prices,
  new_prices,
  changed_fields,
  previous_values_known
)
SELECT
  machine_id,
  name,
  price_updated_at,
  jsonb_build_object('mrp', mrp, 'sell_price', sell_price, 'cost_price', NULL),
  jsonb_build_object('mrp', mrp, 'sell_price', sell_price, 'cost_price', cost_price),
  ARRAY['cost_price']::text[],
  false
FROM updated_machine;
